---
n8n_enabled: false
n8n_hostname: "n8n.{{ domain_root }}"
n8n_timezone: "{{ timezone }}"
n8n_editor_base_url: "https://{{ n8n_hostname }}"
n8n_webhook_url: "https://{{ n8n_hostname }}/"
n8n_image: "docker.n8n.io/n8nio/n8n:latest"
n8n_license_activation_key: ""
n8n_encryption_key: ""
n8n_db_type: "sqlite"
n8n_execution_mode: "regular"
n8n_binary_data_mode: "{{ 'database' if n8n_execution_mode == 'queue' else 'filesystem' }}"
n8n_external_storage_s3_host: ""
n8n_external_storage_s3_bucket_name: ""
n8n_external_storage_s3_bucket_region: "auto"
n8n_external_storage_s3_access_key: ""
n8n_external_storage_s3_access_secret: ""
n8n_postgres_image: "postgres:16-alpine"
n8n_postgres_host: "postgres"
n8n_postgres_port: 5432
n8n_postgres_database: "n8n"
n8n_postgres_user: "n8n"
n8n_postgres_password: ""
n8n_postgres_schema: "public"
n8n_redis_image: "redis:7-alpine"
n8n_redis_host: "redis"
n8n_redis_port: 6379
n8n_redis_db: 0
n8n_redis_password: ""
n8n_worker_replicas: 1
n8n_queue_timeout_threshold: 10000
n8n_graceful_shutdown_timeout: 30
n8n_queue_health_check_active: true
n8n_offload_manual_executions_to_workers: true
n8n_endpoint_health: "/healthz"
n8n_executions_data_save_on_error: "all"
n8n_executions_data_save_on_success: "none"
n8n_executions_data_save_on_progress: false
n8n_executions_data_save_manual_executions: false
